### ISSUE TITLE
System "cepl.examples" not found

### ISSUE THREAD

**Issue by hww** [stacksmith/cepl-youtube-examples#1]
After evaluating:

`* (ql:quickload :cepl.examples)
`
The error message in result:

```
debugger invoked on a QUICKLISP-CLIENT:SYSTEM-NOT-FOUND in thread
#<THREAD "main thread" RUNNING {10019565A3}>:
  System "cepl.examples" not found
```

**Comment by hww** [comment]
BTW The examples from [this repository](https://github.com/cbaggers/cepl.examples
) works

**Comment by stacksmith** [comment]
The repo is hopelessly out of date.  I will be taking it down soon.
